### ISSUE TITLE
Using PHPass library

### ISSUE THREAD

**Issue by pjebs** [jenssegers/codeigniter-authentication-library#3]
Hi Jens.
I don't have a linkedin account so I tried to add you on fb to ask.
I was wondering if it was possible to incorporate your phpass library to this authentication library?

Thanks

PJ (Pee Jai on fb)

**Comment by jenssegers** [comment]
This library is over 2 years old, there are better solutions to do this.

**Comment by pjebs** [comment]
Are you saying the phpass library is too old or your authentication library?
What are the 'better solutions' for authentication?
